version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTests
      - echo Build ended on `date`
  post_build:
    commands:
      - echo Post Build started on `date`
      - mv target/my-blog-api-0.0.1-SNAPSHOT.jar my-blog-api-0.0.1-SNAPSHOT.jar
      - echo Post Build ended on `date`
artifacts:
  files:
    - my-blog-api-0.0.1-SNAPSHOT.jar